import Head from 'next/head'
import Header from "./Header/Header"
import Footer from "./Footer/Footer"
import Newsletter from "./Footer/Newsletter/Newsletter"

export default function Layout({title, children}) {
  return (
    <>
      <Head>
        <title>{title ?? "No Title"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify-between bg-gray-100 scroll-smooth">
        <Header />
        <main className="scroll-smooth ">
          {children}
        </main>
        <Newsletter />
        <Footer />
      </div>
    </>
  );

}
